export const brands = [
  "GE (General Electric)",
  "Baldor Electric Company",
  "Bosch",
  "DeWALT",
  "Makita",
  "Milwaukee Electric Tool Corporation",
  "Black & Decker",
  "Honda",
  "Generac",
  "Kollmorgen",
  "Lincoln Electric",
  "Miller Welding Equipment",
  "AEG",
  "Bodine Electric Company",
  "Fanuc",
  "Lenze",
  "Regal Rexnord",
  "Maxon Group",
  "TECO-Westinghouse",
  "Sumit Engineering Works",
  "Kinetics Industries",
  "Carter Motor Company",
  "MSI (Motor Specialty)",
  "Windtech, Inc.",
  "Sinotech",
  "BDI",
  "Johnson Electric Group",
  "George Stevens Mfg., Inc.",
  "Micafil, Inc.",
  "Itasca Automation Systems, LLC",
  "Liaocheng Mote Electromechanical Co., Ltd",
  "Yongkang Tinen Industrial Co.",
  "Fujian Silkroad Industry Co.",
  "Cleveland Armature Works",
  "Electrex",
  "XTRA-POWER",
  "TRUMAX",
  "Nippon",
  "DCA",
];
